name: Google Indexing Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # JADWAL OTOMATIS (Waktu dalam UTC)
    # Jam 10:00 UTC = 19:00 Korea/Vietnam/Thailand (Puncak Asia)
    # Jam 15:00 UTC = 18:00 Bulgaria/Prancis (Awal Puncak Eropa)
    # Jam 18:00 UTC = 21:00 Prancis/Bulgaria (Puncak Eropa)
    # Jam 22:00 UTC = 19:00 Brazil (Puncak Amerika Latin)
    - cron: '0 10,15,18,22 * * *'

jobs:
  indexing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests google-auth tqdm

      - name: Run Indexing Script
        env:
          INDEXER_CONFIG: ${{ secrets.INDEXER_CONFIG }}
        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add indexed_urls.txt index.html sitemap.xml
          git commit -m "Update database, index, and sitemap [skip ci]" || echo "No changes to commit"
          git push
