name: Google Indexing Bot
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Supaya bisa dijalankan manual
jobs:
  indexing:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Izin untuk menyimpan perubahan ke file indexed_urls.txt
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libs
        run: pip install requests google-auth tqdm google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Run Indexer
        env:
          INDEXER_CONFIG: ${{ secrets.INDEXER_CONFIG }}
        run: python main.py

      - name: Save and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update DB and Sitemaps [skip ci]"
          git pull --rebase origin main
          git push origin main
