name: Google Indexing Bot
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  indexing:
    runs-on: ubuntu-latest
    permissions:
      contents: write # IZIN WAJIB
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Libs
        run: pip install requests google-auth tqdm google-api-python-client
      - name: Run
        env:
          INDEXER_CONFIG: ${{ secrets.INDEXER_CONFIG }}
        run: python main.py
      - name: Save
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update DB, HTML, XML, and Robots [skip ci]" || exit 0
          git push
